  name: DivineCore-AlphaV3
  main: fun.divinetales.Core.CoreMain
  version: V3
  author: Trixy
  api-version: 1.16
  depend:
    - WorldGuard
    - WorldEdit
    - PermissionsEx
    - ProtocolLib
  commands:
    core:
    alignment:
    dungeons:
    dungeonteam:
    hat:
    curse:
    profile:
      description: For players
    playerElement:
      description: Sets a players Element.
    chatspy:
      description: Chat Spy Command.
    ally:
      description: Ally Command.
    chat:
      description: Chat Settings Command.
    join:
    mcreload: